apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None # headless service
  selector:
    name: redis
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      name: redis
      tier: db
  template:
    metadata:
      labels:
        name: redis
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always # or specify a pull policy according to your needs
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-volume
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" # update to match your StorageClass
      resources:
        requests:
          storage: 1Gi
